---
apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-rc
spec:
  replicas: 2
  selector:
    app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        ver: "1.0"
    spec:
     containers:
       - name: simple-pod
         image: jenkins
         ports:
          - containerPort: 8080
...          
